import numpy as np

CATEGORY_SEEDS = {
    "Watches": 1000,
    "Footwear": 2000,
    "Perfumes": 3000,
    "Slippers": 4000,
    "Eyewear": 5000,
    "Electronics": 6000,
}

def generate_category_clustered_vector(category: str, item_seed: int, dim: int = 2048) -> list:
    """Generate a category-clustered L2 normalized 2048-dim embedding vector."""
    cat_seed = CATEGORY_SEEDS.get(category, 2000)
    
    rng_cat = np.random.RandomState(cat_seed)
    cat_center = rng_cat.randn(dim).astype(np.float32)
    cat_center /= np.linalg.norm(cat_center)

    rng_item = np.random.RandomState(item_seed)
    item_noise = rng_item.randn(dim).astype(np.float32)
    item_noise /= np.linalg.norm(item_noise)

    blended = 0.85 * cat_center + 0.15 * item_noise
    blended /= np.linalg.norm(blended)
    return blended.tolist()

INITIAL_CATALOG = [
    # ==================== 10 WATCHES ====================
    {
        "id": "prod-watch-1",
        "name": "Chronos Elegance Automatic Leather Watch",
        "brand": "Vanguard Wristwear",
        "category": "Watches",
        "description": "Handcrafted automatic movement timepiece with sapphire glass crystal, genuine Italian leather strap, and 50m water resistance.",
        "price": 420.00,
        "discount": 20.0,
        "original_price": 525.00,
        "imageUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80"],
        "stock": 12,
        "rating": 4.9,
        "reviewsCount": 115,
        "color": "Silver/Brown",
        "specifications": { "Movement": "Japanese Automatic 21-Jewels", "Case": "316L Stainless Steel" },
        "feature_vector": generate_category_clustered_vector("Watches", 101)
    },
    {
        "id": "prod-watch-2",
        "name": "Titanium Smartwatch Ultra",
        "brand": "PulseWear",
        "category": "Watches",
        "description": "Rugged fitness smartwatch with AMOLED display, dual-frequency GPS, ECG monitor, and up to 14-day battery life.",
        "price": 349.99,
        "discount": 10.0,
        "original_price": 388.87,
        "imageUrl": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80"],
        "stock": 22,
        "rating": 4.8,
        "reviewsCount": 175,
        "color": "Titanium Grey",
        "specifications": { "Display": "1.43\" Sapphire AMOLED", "Battery": "14 Days Typical Use" },
        "feature_vector": generate_category_clustered_vector("Watches", 102)
    },
    {
        "id": "prod-watch-3",
        "name": "Royal Gold Skeleton Mechanical Watch",
        "brand": "Vanguard Wristwear",
        "category": "Watches",
        "description": "Exquisite skeleton dial mechanical watch coated in 18K yellow gold PVD with exhibition case back.",
        "price": 580.00,
        "discount": 15.0,
        "original_price": 682.35,
        "imageUrl": "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&auto=format&fit=crop&q=80"],
        "stock": 8,
        "rating": 4.9,
        "reviewsCount": 64,
        "color": "Polished Gold",
        "specifications": { "Dial": "Full Open Skeleton Work", "Waterproof": "10 ATM / 100M" },
        "feature_vector": generate_category_clustered_vector("Watches", 103)
    },
    {
        "id": "prod-watch-4",
        "name": "Minimalist Rose Gold Mesh Watch",
        "brand": "Milano Atelier",
        "category": "Watches",
        "description": "Ultra-slim 7mm profile wrist watch with rose gold stainless steel mesh strap and pearl white face.",
        "price": 195.00,
        "discount": 12.0,
        "original_price": 221.59,
        "imageUrl": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80"],
        "stock": 16,
        "rating": 4.7,
        "reviewsCount": 92,
        "color": "Rose Gold",
        "specifications": { "Thickness": "7.0 mm Ultra-Thin", "Strap": "Adjustable Stainless Mesh" },
        "feature_vector": generate_category_clustered_vector("Watches", 104)
    },
    {
        "id": "prod-watch-5",
        "name": "Executive Stainless Steel Chronograph",
        "brand": "Vanguard Wristwear",
        "category": "Watches",
        "description": "Precision triple-subdial chronograph watch with tachymeter bezel and solid link stainless steel bracelet.",
        "price": 490.00,
        "discount": 18.0,
        "original_price": 597.56,
        "imageUrl": "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80"],
        "stock": 15,
        "rating": 4.8,
        "reviewsCount": 110,
        "color": "Silver / Blue Dial",
        "specifications": { "Function": "1/10th Sec Chronograph", "Glass": "Anti-Reflective Sapphire" },
        "feature_vector": generate_category_clustered_vector("Watches", 105)
    },
    {
        "id": "prod-watch-6",
        "name": "Vintage Heritage Pocket & Strap Watch",
        "brand": "Milano Atelier",
        "category": "Watches",
        "description": "Retro vintage pocket-style wristwatch featuring aged brass finish, domed glass, and cognac leather strap.",
        "price": 310.00,
        "discount": 10.0,
        "original_price": 344.44,
        "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop&q=80"],
        "stock": 10,
        "rating": 4.6,
        "reviewsCount": 48,
        "color": "Antique Brass / Brown",
        "specifications": { "Finish": "Hand-Brushed Antique Brass", "Crystal": "Domed Mineral Glass" },
        "feature_vector": generate_category_clustered_vector("Watches", 106)
    },
    {
        "id": "prod-watch-7",
        "name": "Aqua Diver Pro 300M Automatic Watch",
        "brand": "Vanguard Wristwear",
        "category": "Watches",
        "description": "Professional 300M water-resistant diver watch with ceramic rotating bezel and luminous hands.",
        "price": 650.00,
        "discount": 15.0,
        "original_price": 764.70,
        "imageUrl": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80"],
        "stock": 7,
        "rating": 4.9,
        "reviewsCount": 82,
        "color": "Deep Ocean Blue",
        "specifications": { "Water Resistance": "300 Meters / 30 ATM", "Bezel": "120-Click Unidirectional Ceramic" },
        "feature_vector": generate_category_clustered_vector("Watches", 107)
    },
    {
        "id": "prod-watch-8",
        "name": "Solar Pulse Sport Digital Watch",
        "brand": "PulseWear",
        "category": "Watches",
        "description": "Solar-recharging outdoor digital watch with shock-resistant case, altimeter, barometer, and compass.",
        "price": 160.00,
        "discount": 10.0,
        "original_price": 177.77,
        "imageUrl": "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&auto=format&fit=crop&q=80"],
        "stock": 25,
        "rating": 4.7,
        "reviewsCount": 140,
        "color": "Tactical Stealth Black",
        "specifications": { "Power": "Tough Solar Battery", "Sensors": "Triple Sensor (ABC)" },
        "feature_vector": generate_category_clustered_vector("Watches", 108)
    },
    {
        "id": "prod-watch-9",
        "name": "Classic Roman Numeral Dress Watch",
        "brand": "Milano Atelier",
        "category": "Watches",
        "description": "Elegant rectangular case dress watch featuring black Roman numerals, blued steel hands, and alligator leather band.",
        "price": 275.00,
        "discount": 12.0,
        "original_price": 312.50,
        "imageUrl": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&auto=format&fit=crop&q=80"],
        "stock": 14,
        "rating": 4.8,
        "reviewsCount": 76,
        "color": "Silver / Black Leather",
        "specifications": { "Dial": "Guilloche Pattern Roman", "Strap": "Alligator Embossed Leather" },
        "feature_vector": generate_category_clustered_vector("Watches", 109)
    },
    {
        "id": "prod-watch-10",
        "name": "Midnight Carbon Fiber Racing Watch",
        "brand": "PulseWear",
        "category": "Watches",
        "description": "High-tech motorsport chronograph with real carbon fiber case, silicone racing strap, and red accent sub-dials.",
        "price": 520.00,
        "discount": 20.0,
        "original_price": 650.00,
        "imageUrl": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80"],
        "stock": 9,
        "rating": 4.9,
        "reviewsCount": 58,
        "color": "Carbon Fiber Black / Red",
        "specifications": { "Case": "Forged Carbon Fiber Composite", "Strap": "Perforated Racing Silicone" },
        "feature_vector": generate_category_clustered_vector("Watches", 110)
    },

    # ==================== 15 SHOES / FOOTWEAR ====================
    {
        "id": "prod-shoe-1",
        "name": "Apex Runner Pro Performance Sneakers",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Ultra-lightweight mesh running shoes with responsive nitrogen-infused foam cushioning and durable rubber grip outsole.",
        "price": 149.99,
        "discount": 15.0,
        "original_price": 176.45,
        "imageUrl": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80"],
        "stock": 25,
        "rating": 4.8,
        "reviewsCount": 128,
        "color": "Red/White",
        "specifications": { "Material": "Engineered Breathable Mesh", "Sole": "High-Traction Rubber" },
        "feature_vector": generate_category_clustered_vector("Footwear", 201)
    },
    {
        "id": "prod-shoe-2",
        "name": "Street Classic White Low-Top Leather Shoes",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Timeless low-top casual sneakers crafted from premium full-grain leather with cushioned memory foam footbed.",
        "price": 110.00,
        "discount": 10.0,
        "original_price": 122.22,
        "imageUrl": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80"],
        "stock": 40,
        "rating": 4.8,
        "reviewsCount": 310,
        "color": "Crisp White",
        "specifications": { "Upper": "100% Full-Grain Leather" },
        "feature_vector": generate_category_clustered_vector("Footwear", 202)
    },
    {
        "id": "prod-shoe-3",
        "name": "Royal Leather Oxford Formal Dress Shoes",
        "brand": "Milano Atelier",
        "category": "Footwear",
        "description": "Hand-burnished Italian leather Oxford shoes featuring closed lacing, Goodyear welt construction, and leather sole.",
        "price": 220.00,
        "discount": 15.0,
        "original_price": 258.82,
        "imageUrl": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80"],
        "stock": 18,
        "rating": 4.9,
        "reviewsCount": 95,
        "color": "Deep Black",
        "specifications": { "Construction": "Goodyear Welted" },
        "feature_vector": generate_category_clustered_vector("Footwear", 203)
    },
    {
        "id": "prod-shoe-4",
        "name": "Velocity Mesh Knit Trail Running Shoes",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "All-terrain trail running shoes with Vibram mega-grip lug outsole and water-resistant breathable lining.",
        "price": 165.00,
        "discount": 20.0,
        "original_price": 206.25,
        "imageUrl": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80"],
        "stock": 21,
        "rating": 4.8,
        "reviewsCount": 97,
        "color": "Olive Green / Orange",
        "specifications": { "Outsole": "Vibram Megagrip Lugs (5mm)" },
        "feature_vector": generate_category_clustered_vector("Footwear", 204)
    },
    {
        "id": "prod-shoe-5",
        "name": "High-Top Retro Basketball Sneakers",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Iconic high-top basketball sneakers crafted with colorblocked leather panels and padded ankle support collars.",
        "price": 175.00,
        "discount": 12.0,
        "original_price": 198.86,
        "imageUrl": "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=800&auto=format&fit=crop&q=80"],
        "stock": 30,
        "rating": 4.9,
        "reviewsCount": 240,
        "color": "Black / Red / White",
        "specifications": { "Style": "High-Top Court Retro", "Cushioning": "Air Heel Unit" },
        "feature_vector": generate_category_clustered_vector("Footwear", 205)
    },
    {
        "id": "prod-shoe-6",
        "name": "Urban Suede Chukka Ankle Boots",
        "brand": "VogueCraft",
        "category": "Footwear",
        "description": "Refined desert chukka boots in soft suede leather with crepe rubber sole and contrast stitching.",
        "price": 190.00,
        "discount": 15.0,
        "original_price": 223.52,
        "imageUrl": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80"],
        "stock": 16,
        "rating": 4.7,
        "reviewsCount": 88,
        "color": "Sand Suede",
        "specifications": { "Upper": "100% Suede Leather", "Sole": "Natural Crepe Rubber" },
        "feature_vector": generate_category_clustered_vector("Footwear", 206)
    },
    {
        "id": "prod-shoe-7",
        "name": "Slip-On Comfort Memory Foam Loafers",
        "brand": "Milano Atelier",
        "category": "Footwear",
        "description": "Handcrafted driving loafers in supple pebbled leather with flexible rubber pebble outsole.",
        "price": 125.00,
        "discount": 10.0,
        "original_price": 138.88,
        "imageUrl": "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80"],
        "stock": 22,
        "rating": 4.8,
        "reviewsCount": 112,
        "color": "Navy Blue",
        "specifications": { "Type": "Slip-On Driver", "Insole": "Cushion Leather Insole" },
        "feature_vector": generate_category_clustered_vector("Footwear", 207)
    },
    {
        "id": "prod-shoe-8",
        "name": "All-Weather Gore-Tex Hiking Boots",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Heavy-duty waterproof mountain hiking boots with Vibram outsole and reinforced rubber toe cap.",
        "price": 210.00,
        "discount": 18.0,
        "original_price": 256.09,
        "imageUrl": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80"],
        "stock": 14,
        "rating": 4.9,
        "reviewsCount": 165,
        "color": "Dark Brown / Orange",
        "specifications": { "Membrane": "Gore-Tex Waterproof", "Lugs": "6mm Mud Grips" },
        "feature_vector": generate_category_clustered_vector("Footwear", 208)
    },
    {
        "id": "prod-shoe-9",
        "name": "Classic Canvas Low-Top Trainers",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Lightweight durable canvas low-top sneakers with vulcanized rubber sole and metal eyelets.",
        "price": 85.00,
        "discount": 10.0,
        "original_price": 94.44,
        "imageUrl": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80"],
        "stock": 50,
        "rating": 4.6,
        "reviewsCount": 320,
        "color": "Black / White Sole",
        "specifications": { "Upper": "Heavy Canvas", "Sole": "Vulcanized Rubber" },
        "feature_vector": generate_category_clustered_vector("Footwear", 209)
    },
    {
        "id": "prod-shoe-10",
        "name": "Italian Leather Monk Strap Dress Shoes",
        "brand": "Milano Atelier",
        "category": "Footwear",
        "description": "Double monk strap formal shoes in hand-burnished cognac calfskin leather with polished brass buckles.",
        "price": 245.00,
        "discount": 15.0,
        "original_price": 288.23,
        "imageUrl": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80"],
        "stock": 11,
        "rating": 4.9,
        "reviewsCount": 78,
        "color": "Cognac Leather",
        "specifications": { "Closure": "Double Metal Buckle", "Leather": "Full Grain Italian" },
        "feature_vector": generate_category_clustered_vector("Footwear", 210)
    },
    {
        "id": "prod-shoe-11",
        "name": "Air Cushion Marathon Racing Shoes",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Carbon plate marathon racing shoes engineered for ultra energy return and lightweight speed.",
        "price": 180.00,
        "discount": 10.0,
        "original_price": 200.00,
        "imageUrl": "https://images.unsplash.com/photo-1460353581641-37babbab0fa2?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1460353581641-37babbab0fa2?w=800&auto=format&fit=crop&q=80"],
        "stock": 20,
        "rating": 4.9,
        "reviewsCount": 190,
        "color": "Neon Yellow / Cyan",
        "specifications": { "Plate": "Full-Length Carbon Fiber", "Weight": "195g" },
        "feature_vector": generate_category_clustered_vector("Footwear", 211)
    },
    {
        "id": "prod-shoe-12",
        "name": "Lightweight Gym Cross-Trainer Shoes",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Stable flat-sole cross training shoes designed for heavy deadlifts, squats, and HIIT workouts.",
        "price": 135.00,
        "discount": 12.0,
        "original_price": 153.40,
        "imageUrl": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80"],
        "stock": 28,
        "rating": 4.7,
        "reviewsCount": 130,
        "color": "Stealth Grey / Lime",
        "specifications": { "Heel Drop": "4mm Flat Heel", "Upper": "Kevlar Reinforced Mesh" },
        "feature_vector": generate_category_clustered_vector("Footwear", 212)
    },
    {
        "id": "prod-shoe-13",
        "name": "Waterproof Winter Snow Boots",
        "brand": "VogueCraft",
        "category": "Footwear",
        "description": "Thermal insulated winter snow boots rated for -30°C temperatures with faux shearling lining.",
        "price": 230.00,
        "discount": 20.0,
        "original_price": 287.50,
        "imageUrl": "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800&auto=format&fit=crop&q=80"],
        "stock": 13,
        "rating": 4.8,
        "reviewsCount": 105,
        "color": "Charcoal / Black",
        "specifications": { "Temp Rating": "-30°C / -22°F", "Insulation": "Thinsulate 400g" },
        "feature_vector": generate_category_clustered_vector("Footwear", 213)
    },
    {
        "id": "prod-shoe-14",
        "name": "Vintage Leather Derby Shoes",
        "brand": "Milano Atelier",
        "category": "Footwear",
        "description": "Casual vintage derby shoes in open-lacing distressed leather with contrast lug sole.",
        "price": 195.00,
        "discount": 15.0,
        "original_price": 229.41,
        "imageUrl": "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?w=800&auto=format&fit=crop&q=80"],
        "stock": 17,
        "rating": 4.7,
        "reviewsCount": 64,
        "color": "Distressed Brown",
        "specifications": { "Lacing": "Open Derby Style", "Finish": "Vintage Washed Leather" },
        "feature_vector": generate_category_clustered_vector("Footwear", 214)
    },
    {
        "id": "prod-shoe-15",
        "name": "Eco-Knit Sustainable Lightweight Sneakers",
        "brand": "AeroStride",
        "category": "Footwear",
        "description": "Ultra-flexible eco sneakers knit from 100% recycled ocean plastic thread with sugarcane EVA midsole.",
        "price": 140.00,
        "discount": 10.0,
        "original_price": 155.55,
        "imageUrl": "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=800&auto=format&fit=crop&q=80"],
        "stock": 35,
        "rating": 4.9,
        "reviewsCount": 215,
        "color": "Sage Green / White",
        "specifications": { "Sustainability": "100% Recycled Threads", "Midsole": "SweetFoam Sugarcane EVA" },
        "feature_vector": generate_category_clustered_vector("Footwear", 215)
    },

    # ==================== 20 PERFUMES & FRAGRANCES ====================
    {
        "id": "prod-perfume-1",
        "name": "Royal Amber Oud Eau de Parfum",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Opulent unisex fragrance blending rare Cambodian Oud, warm amber, damask rose, and rich vanilla bean notes.",
        "price": 210.00,
        "discount": 15.0,
        "original_price": 247.05,
        "imageUrl": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80"],
        "stock": 19,
        "rating": 4.9,
        "reviewsCount": 142,
        "color": "Amber/Gold",
        "specifications": { "Volume": "100ml / 3.4 fl. oz", "Concentration": "Eau de Parfum (20%)" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 301)
    },
    {
        "id": "prod-perfume-2",
        "name": "Midnight Noir Intense Cologne",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Seductive evening scent with accords of black pepper, smoky cedarwood, Italian bergamot, and leather musk.",
        "price": 185.00,
        "discount": 10.0,
        "original_price": 205.55,
        "imageUrl": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80"],
        "stock": 14,
        "rating": 4.8,
        "reviewsCount": 89,
        "color": "Deep Black",
        "specifications": { "Volume": "100ml / 3.4 fl. oz", "Family": "Smoky Spice & Leather" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 302)
    },
    {
        "id": "prod-perfume-3",
        "name": "Floral Bloom Rose Elegance Perfume",
        "brand": "Maison De Fleur",
        "category": "Perfumes",
        "description": "Enchanting feminine perfume sparkling with fresh peony, Grasse rose petals, white musk, and mandarin zest.",
        "price": 145.00,
        "discount": 20.0,
        "original_price": 181.25,
        "imageUrl": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80"],
        "stock": 25,
        "rating": 4.7,
        "reviewsCount": 168,
        "color": "Soft Pink",
        "specifications": { "Volume": "75ml / 2.5 fl. oz", "Family": "Fresh Floral Rose" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 303)
    },
    {
        "id": "prod-perfume-4",
        "name": "Citrus Breeze Fresh Eau de Toilette",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Invigorating aquatic perfume packed with Calabrian lemon, sea salt breeze, vetiver, and crisp green apple notes.",
        "price": 95.00,
        "discount": 10.0,
        "original_price": 105.55,
        "imageUrl": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80"],
        "stock": 30,
        "rating": 4.6,
        "reviewsCount": 210,
        "color": "Ocean Blue",
        "specifications": { "Volume": "100ml / 3.4 fl. oz", "Family": "Fresh Aquatic Citrus" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 304)
    },
    {
        "id": "prod-perfume-5",
        "name": "Velvet Vanilla Musk Luxury Perfume",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Warm sensual gourmet fragrance with Tahitian vanilla bean, cashmeran, roasted tonka, and creamy sandalwood.",
        "price": 170.00,
        "discount": 15.0,
        "original_price": 200.00,
        "imageUrl": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80"],
        "stock": 21,
        "rating": 4.9,
        "reviewsCount": 180,
        "color": "Cream Amber",
        "specifications": { "Volume": "100ml", "Family": "Gourmand Vanilla Musk" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 305)
    },
    {
        "id": "prod-perfume-6",
        "name": "Aqua Di Ocean Marine Eau de Parfum",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Refreshing ocean splash perfume blending maritime algae, crushed mint leaves, and cedarwood base notes.",
        "price": 160.00,
        "discount": 12.0,
        "original_price": 181.81,
        "imageUrl": "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=800&auto=format&fit=crop&q=80"],
        "stock": 18,
        "rating": 4.8,
        "reviewsCount": 135,
        "color": "Aqua Crystal",
        "specifications": { "Volume": "100ml", "Family": "Marine Aquatic" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 306)
    },
    {
        "id": "prod-perfume-7",
        "name": "Golden Sandalwood Imperial Cologne",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Regal woody cologne centering Mysore sandalwood, cardamom, papyrus, and leather accord.",
        "price": 225.00,
        "discount": 18.0,
        "original_price": 274.39,
        "imageUrl": "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&auto=format&fit=crop&q=80"],
        "stock": 11,
        "rating": 4.9,
        "reviewsCount": 98,
        "color": "Golden Wood",
        "specifications": { "Volume": "100ml", "Family": "Rich Woody Sandalwood" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 307)
    },
    {
        "id": "prod-perfume-8",
        "name": "Sweet Jasmine & Peony Botanical Mist",
        "brand": "Maison De Fleur",
        "category": "Perfumes",
        "description": "Delicate botanical perfume infused with night-blooming jasmine, soft peony, and white peach nectar.",
        "price": 115.00,
        "discount": 10.0,
        "original_price": 127.77,
        "imageUrl": "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&auto=format&fit=crop&q=80"],
        "stock": 28,
        "rating": 4.7,
        "reviewsCount": 150,
        "color": "Peach Pink",
        "specifications": { "Volume": "100ml", "Family": "Botanical Jasmine Floral" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 308)
    },
    {
        "id": "prod-perfume-9",
        "name": "Smoky Leather & Bourbon Cologne",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Intense masculine cologne combining aged oak barrel bourbon, dark leather, tobacco leaf, and amber.",
        "price": 195.00,
        "discount": 15.0,
        "original_price": 229.41,
        "imageUrl": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80"],
        "stock": 15,
        "rating": 4.8,
        "reviewsCount": 112,
        "color": "Smoky Amber",
        "specifications": { "Volume": "100ml", "Family": "Leather Bourbon Tobacco" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 309)
    },
    {
        "id": "prod-perfume-10",
        "name": "Wild Iris & White Lotus EDP",
        "brand": "Maison De Fleur",
        "category": "Perfumes",
        "description": "Serene floral fragrance with wild Florentine iris, aquatic white lotus, and violet leaf accent.",
        "price": 155.00,
        "discount": 12.0,
        "original_price": 176.13,
        "imageUrl": "https://images.unsplash.com/photo-1583445013765-46c20c4a6772?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1583445013765-46c20c4a6772?w=800&auto=format&fit=crop&q=80"],
        "stock": 20,
        "rating": 4.8,
        "reviewsCount": 85,
        "color": "Violet Crystal",
        "specifications": { "Volume": "75ml", "Family": "Powdery Iris & Lotus" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 310)
    },
    {
        "id": "prod-perfume-11",
        "name": "Oriental Spice & Cardamom Perfume",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Exotic fragrance loaded with green cardamom, nutmeg, pink pepper, and smoked guaiac wood.",
        "price": 180.00,
        "discount": 10.0,
        "original_price": 200.00,
        "imageUrl": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80"],
        "stock": 17,
        "rating": 4.7,
        "reviewsCount": 94,
        "color": "Spiced Bronze",
        "specifications": { "Volume": "100ml", "Family": "Oriental Spicy Wood" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 311)
    },
    {
        "id": "prod-perfume-12",
        "name": "Cedar & Bergamot Crisp Cologne",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Fresh mountain wood cologne featuring Italian bergamot, Atlas cedar, and clean musk.",
        "price": 140.00,
        "discount": 15.0,
        "original_price": 164.70,
        "imageUrl": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80"],
        "stock": 24,
        "rating": 4.8,
        "reviewsCount": 160,
        "color": "Crisp Green",
        "specifications": { "Volume": "100ml", "Family": "Woody Citrus Fresh" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 312)
    },
    {
        "id": "prod-perfume-13",
        "name": "Rose Gold Diamond Luxury Parfum",
        "brand": "Maison De Fleur",
        "category": "Perfumes",
        "description": "High-luxury perfume adorned with Bulgarian rose, champaca flower, orange blossom, and amber.",
        "price": 260.00,
        "discount": 20.0,
        "original_price": 325.00,
        "imageUrl": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80"],
        "stock": 8,
        "rating": 5.0,
        "reviewsCount": 72,
        "color": "Rose Gold",
        "specifications": { "Volume": "100ml", "Concentration": "Parfum Extract (30%)" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 313)
    },
    {
        "id": "prod-perfume-14",
        "name": "Fresh Bamboo & Green Tea Fragrance",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Soothing spa-like perfume with green tea leaves, bamboo sap, cucumber water, and white cedar.",
        "price": 105.00,
        "discount": 10.0,
        "original_price": 116.66,
        "imageUrl": "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=800&auto=format&fit=crop&q=80"],
        "stock": 32,
        "rating": 4.7,
        "reviewsCount": 185,
        "color": "Zen Green",
        "specifications": { "Volume": "100ml", "Family": "Green Botanical Tea" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 314)
    },
    {
        "id": "prod-perfume-15",
        "name": "Black Violet & Patchouli Night EDP",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Dark enigmatic evening perfume combining black orchid, dark violet, Indonesian patchouli, and vanilla.",
        "price": 190.00,
        "discount": 15.0,
        "original_price": 223.52,
        "imageUrl": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80"],
        "stock": 14,
        "rating": 4.8,
        "reviewsCount": 108,
        "color": "Midnight Purple",
        "specifications": { "Volume": "100ml", "Family": "Dark Floral Patchouli" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 315)
    },
    {
        "id": "prod-perfume-16",
        "name": "Honey & Sweet Blossom Nectar",
        "brand": "Maison De Fleur",
        "category": "Perfumes",
        "description": "Warm luscious perfume dripping with wild clover honey, almond blossom, and whipped cream musk.",
        "price": 125.00,
        "discount": 10.0,
        "original_price": 138.88,
        "imageUrl": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80"],
        "stock": 26,
        "rating": 4.8,
        "reviewsCount": 130,
        "color": "Golden Honey",
        "specifications": { "Volume": "100ml", "Family": "Sweet Honey Blossom" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 316)
    },
    {
        "id": "prod-perfume-17",
        "name": "Pure Linen & Cotton Soft EDT",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Clean comforting scent reminiscent of sun-dried cotton sheets, aldehydes, white musk, and lily.",
        "price": 88.00,
        "discount": 10.0,
        "original_price": 97.77,
        "imageUrl": "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&auto=format&fit=crop&q=80"],
        "stock": 40,
        "rating": 4.6,
        "reviewsCount": 220,
        "color": "Soft Linen White",
        "specifications": { "Volume": "100ml", "Family": "Clean Aldehydic Musks" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 317)
    },
    {
        "id": "prod-perfume-18",
        "name": "Emerald Fig & Cypress Woody Perfume",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Mediterranean woody scent with wild green fig leaves, Mediterranean cypress, and cedar.",
        "price": 165.00,
        "discount": 15.0,
        "original_price": 194.11,
        "imageUrl": "https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&auto=format&fit=crop&q=80"],
        "stock": 19,
        "rating": 4.8,
        "reviewsCount": 92,
        "color": "Emerald Green",
        "specifications": { "Volume": "100ml", "Family": "Woody Green Fig" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 318)
    },
    {
        "id": "prod-perfume-19",
        "name": "Saffron & Cashmere Elite Cologne",
        "brand": "LuxeParfums",
        "category": "Perfumes",
        "description": "Ultra-exclusive fragrance boasting red Iranian saffron, warm cashmere wood, and ambergris.",
        "price": 240.00,
        "discount": 18.0,
        "original_price": 292.68,
        "imageUrl": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80"],
        "stock": 10,
        "rating": 4.9,
        "reviewsCount": 84,
        "color": "Deep Saffron Red",
        "specifications": { "Volume": "100ml", "Family": "Saffron Cashmere Woody" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 319)
    },
    {
        "id": "prod-perfume-20",
        "name": "Sunlit Citrus & Neroli Summer Mist",
        "brand": "AquaVogue",
        "category": "Perfumes",
        "description": "Radiant summer perfume bursting with Italian neroli blossom, sunlit mandarin, and orange flower water.",
        "price": 110.00,
        "discount": 10.0,
        "original_price": 122.22,
        "imageUrl": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80"],
        "stock": 35,
        "rating": 4.7,
        "reviewsCount": 170,
        "color": "Sunlit Orange",
        "specifications": { "Volume": "100ml", "Family": "Solar Neroli Citrus" },
        "feature_vector": generate_category_clustered_vector("Perfumes", 320)
    },

    # ==================== SLIPPERS & SLIDES ====================
    {
        "id": "prod-slipper-1",
        "name": "Cozy Cloud Plush Velvet House Slippers",
        "brand": "ComfortSole",
        "category": "Slippers",
        "description": "Ultra-soft indoor slippers featuring thick high-density memory foam padding and non-slip rubber indoor/outdoor sole.",
        "price": 45.00,
        "discount": 15.0,
        "original_price": 52.94,
        "imageUrl": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80"],
        "stock": 45,
        "rating": 4.8,
        "reviewsCount": 310,
        "color": "Cream Beige",
        "specifications": { "Upper": "Soft Velvet Fleece", "Sole": "Anti-Slip Waterproof Rubber" },
        "feature_vector": generate_category_clustered_vector("Slippers", 401)
    },
    {
        "id": "prod-slipper-2",
        "name": "Ergonomic Memory Foam Recovery Slides",
        "brand": "ComfortSole",
        "category": "Slippers",
        "description": "Impact-absorbing EVA foam athletic slides engineered for post-workout foot fatigue recovery and arch support.",
        "price": 38.00,
        "discount": 10.0,
        "original_price": 42.22,
        "imageUrl": "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&auto=format&fit=crop&q=80"],
        "stock": 50,
        "rating": 4.7,
        "reviewsCount": 198,
        "color": "Charcoal Grey",
        "specifications": { "Material": "Injection Molded Cloud EVA" },
        "feature_vector": generate_category_clustered_vector("Slippers", 402)
    },
    {
        "id": "prod-slipper-3",
        "name": "Luxe Faux Fur Fluffy House Slides",
        "brand": "ComfortSole",
        "category": "Slippers",
        "description": "Chic open-toe house slides lined with premium plush faux fur for maximum warmth and lounging style.",
        "price": 55.00,
        "discount": 20.0,
        "original_price": 68.75,
        "imageUrl": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80"],
        "stock": 35,
        "rating": 4.9,
        "reviewsCount": 140,
        "color": "Dusty Rose",
        "specifications": { "Lining": "100% Eco Faux Fur" },
        "feature_vector": generate_category_clustered_vector("Slippers", 403)
    },
    {
        "id": "prod-slipper-4",
        "name": "Leather Casual Summer Strap Sandals",
        "brand": "AeroStride",
        "category": "Slippers",
        "description": "Handstitched full-grain leather sandals with adjustable buckle straps and contoured cork footbed.",
        "price": 85.00,
        "discount": 15.0,
        "original_price": 100.00,
        "imageUrl": "https://images.unsplash.com/photo-1621249269836-3b06c8868511?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1621249269836-3b06c8868511?w=800&auto=format&fit=crop&q=80"],
        "stock": 28,
        "rating": 4.6,
        "reviewsCount": 85,
        "color": "Tan Brown",
        "specifications": { "Upper": "100% Calfskin Leather" },
        "feature_vector": generate_category_clustered_vector("Slippers", 404)
    },
    {
        "id": "prod-slipper-5",
        "name": "Shearling Lined Winter Bootie Slippers",
        "brand": "ComfortSole",
        "category": "Slippers",
        "description": "Ultra-warm ankle bootie slippers lined with real Australian shearling wool and sturdy rubber traction sole.",
        "price": 68.00,
        "discount": 12.0,
        "original_price": 77.27,
        "imageUrl": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80",
        "gallery": ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80"],
        "stock": 20,
        "rating": 4.9,
        "reviewsCount": 110,
        "color": "Chestnut Brown",
        "specifications": { "Lining": "100% Australian Shearling Wool" },
        "feature_vector": generate_category_clustered_vector("Slippers", 405)
    }
]
